language: node_js
node_js:
- 7
sudo: false
os:
- linux
cache:
  directories: node_modules
before_script:
  - npm install grunt-cli -g
after_success:
  - grunt
deploy:
  provider: npm
  email: me@michiweber.de
  api_key: cf46048c-cf59-4b11-a9fa-6d256d7bd7f0
  on:
    tags: true
